"""Add player props and parlay fields to Bet model

Revision ID: 1594c8d21bfb
Revises: 5dbf83d99b77
Create Date: 2026-02-24 22:55:01.367696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1594c8d21bfb'
down_revision = '5dbf83d99b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('prop_type', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('prop_line', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('parlay_id', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.drop_column('parlay_id')
        batch_op.drop_column('prop_line')
        batch_op.drop_column('prop_type')
        batch_op.drop_column('player_name')

    # ### end Alembic commands ###
