"""scenario context pack

Revision ID: 21dc7a4c6b61
Revises: 48b0294647d9
Create Date: 2026-07-17 13:48:08.064703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21dc7a4c6b61'
down_revision = '48b0294647d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario_context_pack',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sport', sa.String(length=10), nullable=False),
        sa.Column('payload', sa.Text(), nullable=False),
        sa.Column('computed_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('sport')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_context_pack')
    # ### end Alembic commands ###
