"""add odds_snapshots

Revision ID: 37824fa75dbc
Revises: c3a1f7e82b04
Create Date: 2026-03-08 20:37:38.295484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37824fa75dbc'
down_revision = 'c3a1f7e82b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=True),
    sa.Column('game_date', sa.Date(), nullable=True),
    sa.Column('player_name', sa.String(length=100), nullable=True),
    sa.Column('market', sa.String(length=60), nullable=True),
    sa.Column('bookmaker', sa.String(length=30), nullable=True),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('over_odds', sa.Integer(), nullable=True),
    sa.Column('under_odds', sa.Integer(), nullable=True),
    sa.Column('snapped_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('odds_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_odds_snap_composite', ['game_date', 'game_id', 'player_name', 'market', 'bookmaker'], unique=False)
        batch_op.create_index(batch_op.f('ix_odds_snapshots_game_date'), ['game_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_odds_snapshots_game_id'), ['game_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('odds_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_odds_snapshots_game_id'))
        batch_op.drop_index(batch_op.f('ix_odds_snapshots_game_date'))
        batch_op.drop_index('ix_odds_snap_composite')

    op.drop_table('odds_snapshots')
    # ### end Alembic commands ###
