"""add scenario split and game odds

Revision ID: 48b0294647d9
Revises: 4915f60474d8
Create Date: 2026-07-10 20:00:46.241418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b0294647d9'
down_revision = '4915f60474d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_game_odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('home_abbr', sa.String(length=10), nullable=False),
    sa.Column('away_abbr', sa.String(length=10), nullable=False),
    sa.Column('spread', sa.Float(), nullable=False),
    sa.Column('favored', sa.String(length=4), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('moneyline_home', sa.Float(), nullable=True),
    sa.Column('moneyline_away', sa.Float(), nullable=True),
    sa.Column('is_playoff', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('espn_game_id', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_date', 'home_abbr', name='uq_game_odds_date_home')
    )
    with op.batch_alter_table('historical_game_odds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historical_game_odds_game_date'), ['game_date'], unique=False)

    op.create_table('scenario_split',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=10), nullable=False),
    sa.Column('player_id', sa.String(length=20), nullable=False),
    sa.Column('player_name', sa.String(length=120), nullable=False),
    sa.Column('stat', sa.String(length=20), nullable=False),
    sa.Column('dim1', sa.String(length=30), nullable=False),
    sa.Column('bucket1', sa.String(length=20), nullable=False),
    sa.Column('dim2', sa.String(length=30), nullable=True),
    sa.Column('bucket2', sa.String(length=20), nullable=True),
    sa.Column('season_scope', sa.String(length=10), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('raw_mean', sa.Float(), nullable=False),
    sa.Column('shrunk_mean', sa.Float(), nullable=False),
    sa.Column('baseline_mean', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport', 'player_id', 'stat', 'dim1', 'bucket1', 'dim2', 'bucket2', 'season_scope', name='uq_scenario_split_key')
    )
    with op.batch_alter_table('scenario_split', schema=None) as batch_op:
        batch_op.create_index('ix_scenario_split_lookup', ['sport', 'player_id', 'stat'], unique=False)

    # Redundant single-column index: fully covered by the composite indexes
    # ix_hist_sport_player_date and ix_hist_sport_season (both prefixed by
    # `sport`). Deferred follow-up from Plan A.
    op.drop_index('ix_historical_game_log_sport', table_name='historical_game_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_historical_game_log_sport', 'historical_game_log', ['sport'], unique=False)

    with op.batch_alter_table('scenario_split', schema=None) as batch_op:
        batch_op.drop_index('ix_scenario_split_lookup')

    op.drop_table('scenario_split')
    with op.batch_alter_table('historical_game_odds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_game_odds_game_date'))

    op.drop_table('historical_game_odds')
    # ### end Alembic commands ###
