"""add historical_game_log table

Revision ID: 4915f60474d8
Revises: 48c0bd443cd3
Create Date: 2026-07-08 16:23:49.500896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4915f60474d8'
down_revision = '48c0bd443cd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_game_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=10), nullable=False),
    sa.Column('player_id', sa.String(length=20), nullable=False),
    sa.Column('player_name', sa.String(length=120), nullable=False),
    sa.Column('team_abbr', sa.String(length=10), nullable=True),
    sa.Column('opp_abbr', sa.String(length=10), nullable=True),
    sa.Column('game_id', sa.String(length=30), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('home_away', sa.String(length=4), nullable=True),
    sa.Column('win_loss', sa.String(length=1), nullable=True),
    sa.Column('starter', sa.Boolean(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport', 'player_id', 'game_id', name='uq_hist_sport_player_game')
    )
    with op.batch_alter_table('historical_game_log', schema=None) as batch_op:
        batch_op.create_index('ix_hist_sport_player_date', ['sport', 'player_name', 'game_date'], unique=False)
        batch_op.create_index('ix_hist_sport_season', ['sport', 'season'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_game_log_sport'), ['sport'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_game_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_game_log_sport'))
        batch_op.drop_index('ix_hist_sport_season')
        batch_op.drop_index('ix_hist_sport_player_date')

    op.drop_table('historical_game_log')
    # ### end Alembic commands ###
