"""Add player stats defense injuries pickcontext model metadata job log

Revision ID: 57622ba64816
Revises: c6c23cce68d8
Create Date: 2026-02-26 17:53:01.455820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57622ba64816'
down_revision = 'c6c23cce68d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('injury_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=120), nullable=False),
    sa.Column('team', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.String(length=300), nullable=True),
    sa.Column('date_reported', sa.Date(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=80), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('model_type', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('file_path', sa.String(length=300), nullable=False),
    sa.Column('training_date', sa.DateTime(), nullable=False),
    sa.Column('training_samples', sa.Integer(), nullable=True),
    sa.Column('val_mae', sa.Float(), nullable=True),
    sa.Column('val_accuracy', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_game_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=20), nullable=False),
    sa.Column('player_name', sa.String(length=120), nullable=False),
    sa.Column('team_abbr', sa.String(length=10), nullable=True),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('matchup', sa.String(length=40), nullable=True),
    sa.Column('minutes', sa.Float(), nullable=True),
    sa.Column('pts', sa.Float(), nullable=True),
    sa.Column('reb', sa.Float(), nullable=True),
    sa.Column('ast', sa.Float(), nullable=True),
    sa.Column('stl', sa.Float(), nullable=True),
    sa.Column('blk', sa.Float(), nullable=True),
    sa.Column('tov', sa.Float(), nullable=True),
    sa.Column('fgm', sa.Float(), nullable=True),
    sa.Column('fga', sa.Float(), nullable=True),
    sa.Column('ftm', sa.Float(), nullable=True),
    sa.Column('fta', sa.Float(), nullable=True),
    sa.Column('fg3m', sa.Float(), nullable=True),
    sa.Column('fg3a', sa.Float(), nullable=True),
    sa.Column('plus_minus', sa.Float(), nullable=True),
    sa.Column('home_away', sa.String(length=4), nullable=True),
    sa.Column('win_loss', sa.String(length=1), nullable=True),
    sa.Column('context_flags', sa.Text(), nullable=True),
    sa.Column('cache_expires', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_date', name='uq_player_game_date')
    )
    with op.batch_alter_table('player_game_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_game_log_player_id'), ['player_id'], unique=False)

    op.create_table('team_defense_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=20), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('team_abbr', sa.String(length=10), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('opp_pts_pg', sa.Float(), nullable=True),
    sa.Column('opp_reb_pg', sa.Float(), nullable=True),
    sa.Column('opp_ast_pg', sa.Float(), nullable=True),
    sa.Column('opp_3pm_pg', sa.Float(), nullable=True),
    sa.Column('opp_stl_pg', sa.Float(), nullable=True),
    sa.Column('opp_blk_pg', sa.Float(), nullable=True),
    sa.Column('opp_tov_pg', sa.Float(), nullable=True),
    sa.Column('pace', sa.Float(), nullable=True),
    sa.Column('def_rating', sa.Float(), nullable=True),
    sa.Column('opp_pts_allowed_pg', sa.Float(), nullable=True),
    sa.Column('opp_pts_allowed_sg', sa.Float(), nullable=True),
    sa.Column('opp_pts_allowed_sf', sa.Float(), nullable=True),
    sa.Column('opp_pts_allowed_pf', sa.Float(), nullable=True),
    sa.Column('opp_pts_allowed_c', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'snapshot_date', name='uq_team_defense_date')
    )
    op.create_table('pick_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bet_id', sa.Integer(), nullable=False),
    sa.Column('context_json', sa.Text(), nullable=False),
    sa.Column('projected_stat', sa.Float(), nullable=True),
    sa.Column('projected_edge', sa.Float(), nullable=True),
    sa.Column('confidence_tier', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bet_id'], ['bet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pick_context')
    op.drop_table('team_defense_snapshot')
    with op.batch_alter_table('player_game_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_game_log_player_id'))

    op.drop_table('player_game_log')
    op.drop_table('model_metadata')
    op.drop_table('job_log')
    op.drop_table('injury_report')
    # ### end Alembic commands ###
