"""Add bet_type, over_under_line, actual_total, external_game_id to Bet

Revision ID: 5dbf83d99b77
Revises: 8f2b1d4c0a11
Create Date: 2026-02-24 22:12:24.385543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dbf83d99b77'
down_revision = '8f2b1d4c0a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bet_type', sa.String(length=20), nullable=False, server_default='moneyline'))
        batch_op.add_column(sa.Column('over_under_line', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('actual_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('external_game_id', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.drop_column('external_game_id')
        batch_op.drop_column('actual_total')
        batch_op.drop_column('over_under_line')
        batch_op.drop_column('bet_type')

    # ### end Alembic commands ###
