"""add picked_team to bet

Revision ID: 8b9478dd7d82
Revises: 1594c8d21bfb
Create Date: 2026-02-25 07:46:17.559405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9478dd7d82'
down_revision = '1594c8d21bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picked_team', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.drop_column('picked_team')

    # ### end Alembic commands ###
