"""cascade_delete_pick_context

Revision ID: b6f9fdecc99a
Revises: 12d4e93f7a10
Create Date: 2026-03-01 19:56:53.000190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f9fdecc99a'
down_revision = '12d4e93f7a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pick_context', schema=None) as batch_op:
        batch_op.drop_constraint('pick_context_bet_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bet', ['bet_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pick_context', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pick_context_bet_id_fkey', 'bet', ['bet_id'], ['id'])

    # ### end Alembic commands ###
