"""Initial migration

Revision ID: df40be11245b
Revises: b99f363d0c73
Create Date: 2025-01-16 18:50:23.026345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df40be11245b'
down_revision = 'b99f363d0c73'
branch_labels = None
depends_on = None


def upgrade():
    # NOTE:
    # The previous migration already creates the `user` and `bet` tables.
    # This revision should only reshape the bet table to the current model.
    # Re-creating `user` here causes `table user already exists` failures.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bet')
    op.create_table('bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_a', sa.String(length=80), nullable=False),
    sa.Column('team_b', sa.String(length=80), nullable=False),
    sa.Column('match_date', sa.DateTime(), nullable=False),
    sa.Column('bet_amount', sa.Float(), nullable=False),
    sa.Column('outcome', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bet')
    op.create_table('bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('match', sa.String(length=100), nullable=False),
    sa.Column('bet_detail', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('bet_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
